# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_LoginMain(object):
    def setupUi(self, LoginMain):
        LoginMain.setObjectName("LoginMain")
        LoginMain.resize(1281, 684)
        LoginMain.setMaximumSize(QtCore.QSize(1281, 684))
        LoginMain.setStyleSheet("QLineEdit{\n"
"border:none;\n"
"}\n"
"QPushButton{\n"
"background-color: #ffffff;\n"
"border-radius: 10px;\n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(LoginMain)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1631, 831))
        self.label.setStyleSheet("background-image: url(:/res/login_bg/login_bg2.JPG);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(470, 410, 111, 31))
        self.btn_login.setObjectName("btn_login")
        self.btn_quit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quit.setGeometry(QtCore.QRect(660, 410, 111, 31))
        self.btn_quit.setObjectName("btn_quit")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(500, 289, 271, 31))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(500, 348, 271, 31))
        self.password.setObjectName("password")
        self.btn_href = QtWidgets.QPushButton(self.centralwidget)
        self.btn_href.setGeometry(QtCore.QRect(537, 460, 181, 26))
        self.btn_href.setObjectName("btn_href")
        # LoginMain.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LoginMain)
        self.statusbar.setObjectName("statusbar")
        # LoginMain.setStatusBar(self.statusbar)

        self.retranslateUi(LoginMain)
        QtCore.QMetaObject.connectSlotsByName(LoginMain)

    def retranslateUi(self, LoginMain):
        _translate = QtCore.QCoreApplication.translate
        LoginMain.setWindowTitle(_translate("LoginMain", "LoginMain"))
        LoginMain.setWindowFlags(Qt.FramelessWindowHint)  # 隐藏窗体标题栏
        LoginMain.setAttribute(QtCore.Qt.WA_TranslucentBackground)  # 将窗体背景变透明
        self.btn_login.setText(_translate("LoginMain", "登录"))
        self.btn_quit.setText(_translate("LoginMain", "退出"))
        self.btn_href.setText(_translate("LoginMain", "没有账号？点击注册"))
import res.img_rc
